"use client";
import { useEffect, useState } from "react";
import type { User } from "firebase/auth";
import type { ManagedUser } from "@/lib/admin-users";
import { permissionLabels, type AccessRole, type Permission } from "@/lib/admin-permissions";
import { adminRequest } from "./admin-client";
export function AdminUsers({user,onSaved}:{user:User;onSaved:()=>Promise<void>}) {
  const [users,setUsers]=useState<ManagedUser[]>([]);const [loaded,setLoaded]=useState(false);
  const [search,setSearch]=useState("");const [selected,setSelected]=useState<ManagedUser|null>(null);
  const [role,setRole]=useState<AccessRole>("user");const [permissions,setPermissions]=useState<Permission[]>([]);
  const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);
  useEffect(()=>{let active=true;void adminRequest<{users:ManagedUser[]}>(user,"users").then(result=>{if(active){setUsers(result.users);setLoaded(true);}}).catch(error=>{if(active)setMessage(error instanceof Error?error.message:"Falha ao carregar usuários.");});return()=>{active=false;};},[user]);
  return <div className="admin-users"><p>{loaded?`${users.length} usuários cadastrados no Firebase Authentication.`:"Carregando usuários…"} Funcionários precisam entrar com Google ao menos uma vez para aparecer aqui.</p>{message && <p role="status" className="admin-notice">{message}</p>}<label>Buscar usuário<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Nome ou e-mail" /></label><div className="admin-reference-list">{users.filter(item=>`${item.name} ${item.email}`.toLowerCase().includes(search.toLowerCase())).map(item=><div className="admin-user-row" key={item.uid}><div><strong>{item.name}</strong><small>{item.email}</small><small>{item.owner?"Administrador principal":item.role==="administrator"?"Administrador":item.role==="employee"?"Funcionário":"Usuário"}{item.disabled?" · Conta desativada":""}</small></div><button className="button secondary" disabled={busy || item.owner || item.uid===user.uid} onClick={()=>{setSelected(item);setRole(item.role);setPermissions(item.permissions);setMessage("");}}>Gerenciar acesso</button></div>)}</div>{selected && <form className="admin-card" onSubmit={async event=>{event.preventDefault();setBusy(true);setMessage("");try{await adminRequest(user,"users",{method:"PATCH",body:JSON.stringify({uid:selected.uid,role,permissions})});const result=await adminRequest<{users:ManagedUser[]}>(user,"users");setUsers(result.users);setSelected(null);setMessage("Acesso atualizado. As novas permissões já valem nas APIs; o funcionário deve atualizar o painel.");await onSaved();}catch(error){setMessage(error instanceof Error?error.message:"Falha ao salvar.");}finally{setBusy(false);}}}><h2>Acesso de {selected.name}</h2><fieldset disabled={busy}><label>Perfil<select value={role} onChange={event=>setRole(event.target.value as AccessRole)}><option value="user">Usuário — sem painel administrativo</option><option value="employee">Funcionário — acessos selecionados</option><option value="administrator">Administrador — todos os módulos e usuários</option></select></label>{role==="employee" && <div><p>Selecione os módulos e ações permitidos. Cadastrar, editar ou importar produtos também libera a visualização de produtos.</p>{Object.entries(permissionLabels).map(([key,label])=><label className="admin-checkbox" key={key}><input type="checkbox" checked={permissions.includes(key as Permission)} onChange={event=>setPermissions(old=>event.target.checked?[...old,key as Permission]:old.filter(item=>item!==key))} />{label}</label>)}</div>}<div className="admin-access-actions"><button className="button primary">Salvar acesso</button><button type="button" className="button secondary" onClick={()=>setSelected(null)}>Cancelar</button></div></fieldset></form>}</div>;
}
