import assert from 'node:assert/strict';
import { testReactions } from './reactions-emulator.mjs';
import { testAdminStore } from './admin-emulator.mjs';
import ts from 'typescript';
import { initializeApp, deleteApp } from 'firebase-admin/app';
import { getFirestore as adminDatabase } from 'firebase-admin/firestore';
import { readFile } from 'node:fs/promises';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, setDoc, getDoc, deleteDoc, collection, getDocs, serverTimestamp, query, where, orderBy } from 'firebase/firestore';
const env=await initializeTestEnvironment({projectId:'demo-comparacel',firestore:{host:'127.0.0.1',port:8089,rules:await readFile('firestore.rules','utf8')}});
try {
 await env.withSecurityRulesDisabled(async context => {
  for(const [id,category,isActive] of [['a','celulares',true],['b','celulares',true],['laptop','notebooks',true],['inactive','celulares',false]]) await setDoc(doc(context.firestore(),'products',id),{categorySlug:category,isActive});
 });
 const alice=env.authenticatedContext('alice').firestore();
 const bob=env.authenticatedContext('bob').firestore();
 const guest=env.unauthenticatedContext().firestore();
 const product={productId:'a',createdAt:serverTimestamp()};
 await assertSucceeds(setDoc(doc(alice,'users/alice/likedProducts/a'),product));
 await assertSucceeds(getDoc(doc(alice,'users/alice/likedProducts/a')));
 await assertFails(getDoc(doc(bob,'users/alice/likedProducts/a')));
 await assertFails(getDocs(collection(bob,'users/alice/likedProducts')));
 await assertFails(getDoc(doc(guest,'users/alice/likedProducts/a')));
 await assertFails(setDoc(doc(bob,'users/alice/likedProducts/a'),product));
 await assertFails(setDoc(doc(guest,'users/alice/likedProducts/a'),product));
 await assertFails(setDoc(doc(alice,'users/alice/likedProducts/nonexistent'),{productId:'nonexistent',createdAt:serverTimestamp()}));
 await assertFails(setDoc(doc(alice,'users/alice/likedProducts/inactive'),{productId:'inactive',createdAt:serverTimestamp()}));
 await assertFails(setDoc(doc(alice,'users/alice/likedProducts/a'),{...product,admin:true}));
 for(const kind of ['likedComparisons','savedComparisons']) {
  const path=`users/alice/${kind}/a-vs-b`;
  await assertSucceeds(setDoc(doc(alice,path),{productIds:['a','b'],createdAt:serverTimestamp()}));
  await assertSucceeds(getDoc(doc(alice,path)));
  await assertFails(getDoc(doc(bob,path)));
  await assertFails(getDoc(doc(guest,path)));
  await assertFails(setDoc(doc(alice,`users/alice/${kind}/a-vs-laptop`),{productIds:['a','laptop'],createdAt:serverTimestamp()}));
  await assertFails(setDoc(doc(alice,`users/alice/${kind}/a-vs-a`),{productIds:['a','a'],createdAt:serverTimestamp()}));
  await assertSucceeds(deleteDoc(doc(alice,path)));
 }
 await assertSucceeds(deleteDoc(doc(alice,'users/alice/likedProducts/a')));
 await assertSucceeds(getDoc(doc(guest,'products/a')));
 await assertFails(getDoc(doc(guest,'products/inactive')));
 await assertFails(setDoc(doc(alice,'products/a'),{isActive:true}));
 const profile={displayName:'Alice',bio:'Comparo antes de comprar.',photoURL:null,updatedAt:serverTimestamp()};
 await assertSucceeds(setDoc(doc(alice,'profiles/alice'),profile));
 await assertSucceeds(getDoc(doc(guest,'profiles/alice')));
 await assertFails(setDoc(doc(bob,'profiles/alice'),profile));
 await assertFails(setDoc(doc(alice,'profiles/alice'),{...profile,email:'private@example.com'}));
 const post={authorUid:'alice',authorName:'Alice',authorPhoto:null,title:'Minha comparação',opinion:'Esta é minha opinião sobre os dois produtos.',productIds:['a','b'],category:'celulares',winner:'a',status:'published',createdAt:serverTimestamp()};
 await assertSucceeds(setDoc(doc(alice,'socialPosts/first'),post));
 await assertSucceeds(getDoc(doc(guest,'socialPosts/first')));
 await assertSucceeds(getDocs(query(collection(guest,'socialPosts'),where('status','==','published'),orderBy('createdAt','desc'))));
 await assertFails(setDoc(doc(guest,'socialPosts/guest'),post));
 await assertFails(setDoc(doc(bob,'socialPosts/forged'),post));
 for(const invalid of [{authorName:'Bob'},{productIds:['a','laptop']},{winner:'laptop'},{status:'draft'},{email:'private@example.com'}]) await assertFails(setDoc(doc(alice,'socialPosts/invalid'),{...post,...invalid}));
 await assertFails(setDoc(doc(alice,'socialPosts/first'),{...post,title:'Alterado'}));
 await assertFails(deleteDoc(doc(bob,'socialPosts/first')));
 await assertSucceeds(deleteDoc(doc(alice,'socialPosts/first')));
 console.log('Perfis e publicações: leitura pública, autoria, validação, privacidade e retirada verificadas.');
 const compile=source=>ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
 const dataUrl=source=>`data:text/javascript;base64,${Buffer.from(source).toString('base64')}`;
 const modelUrl=dataUrl(compile(await readFile('lib/engagement-model.ts','utf8')));
 const activityUrl=dataUrl(compile(await readFile('lib/comparison-activity.ts','utf8')));
 const storeSource=compile(await readFile('lib/engagement-store.ts','utf8')).replace('"firebase-admin/firestore"',JSON.stringify(import.meta.resolve('firebase-admin/firestore'))).replace('"./engagement-model"',JSON.stringify(modelUrl)).replace('"./comparison-activity"',JSON.stringify(activityUrl));
 const {recordVisit,readCounts}=await import(dataUrl(storeSource));
 const {pageIdentity,VISIT_WINDOW_MS}=await import(modelUrl);
 const admin=initializeApp({projectId:'demo-comparacel'},'metrics-test');
 try {
  const db=adminDatabase(admin);
  const identity=pageIdentity('product',['a']);
  const now=Date.now();
  await Promise.all(Array.from({length:4},()=>recordVisit(db,identity,'same-browser',now)));
  assert.equal((await readCounts(db,identity)).views,1);
  await recordVisit(db,identity,'same-browser',now+VISIT_WINDOW_MS-1);
  assert.equal((await readCounts(db,identity)).views,1);
  await recordVisit(db,identity,'same-browser',now+VISIT_WINDOW_MS);
  await recordVisit(db,identity,'another-browser',now);
  assert.equal((await readCounts(db,identity)).views,3);
  assert.equal(await recordVisit(db,pageIdentity('product',['inactive']),'visitor',now),false);
  assert.equal(await recordVisit(db,pageIdentity('comparison',['a','laptop']),'visitor',now),false);
  await recordVisit(db,pageIdentity('comparison',['b','a']),'visitor',now);
  await recordVisit(db,pageIdentity('comparison',['a','b']),'visitor',now);
  assert.equal((await readCounts(db,pageIdentity('comparison',['a','b']))).views,1);
  const {readPopularComparisons}=await import(activityUrl);
  assert.equal((await readPopularComparisons(db,now))[0].views,1);
  assert.deepEqual((await readPopularComparisons(db,now))[0].productIds,['a','b']);
  await recordVisit(db,pageIdentity('comparison',['a','b']),'other-visitor',now);
  assert.equal((await readPopularComparisons(db,now))[0].views,2);
  assert.equal((await readPopularComparisons(db,now+7*24*60*60*1000)).length,0);
  await assertSucceeds(setDoc(doc(alice,'users/alice/likedProducts/a'),product));
  await assertSucceeds(setDoc(doc(bob,'users/bob/likedProducts/a'),product));
  assert.equal((await readCounts(db,identity)).likes,2);
  await assertSucceeds(deleteDoc(doc(alice,'users/alice/likedProducts/a')));
  assert.equal((await readCounts(db,identity)).likes,1);
  await assertFails(getDoc(doc(guest,'pageStats/product:a/visitors/same-browser')));
  await assertFails(setDoc(doc(alice,'pageStats/product:a'),{views:9999}));
  console.log('Contadores validados: concorrência, recarga, 30 minutos, pares canônicos, totais de gostei e privacidade.');
 } finally {await deleteApp(admin);}
 await testReactions(env);
 await testAdminStore(env);
 console.log('Regras validadas: dono da conta, isolamento, visitantes, produtos ativos, pares compatíveis e remoção.');
} finally {await env.cleanup();}
