import { test, expect } from "@playwright/test";

test("seleção, troca, comparação completa e navegação", async ({ page }) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await page.goto("/comparar");
  const first = page.getByLabel("Produto 1", { exact: true });
  await expect(first).toBeVisible({timeout:30000});
  await expect.poll(() => first.locator("option").count()).toBeGreaterThan(3);
  const ids = await first.locator("option").evaluateAll(options => options.map(option => (option as HTMLOptionElement).value).filter(Boolean));
  await first.selectOption(ids[0]);
  const second = page.getByLabel("Produto 2", { exact: true });
  await second.selectOption(ids[1]);
  // Replacing a filled slot must immediately select the newly chosen product.
  await second.selectOption(ids[2]);
  await expect(first).toHaveValue(ids[0]);
  await expect(second).toHaveValue(ids[2]);
  await page.getByRole("link", { name: "Ver comparação completa" }).click();
  await expect(page).toHaveURL(new RegExp(`/comparar/${[ids[0], ids[2]].sort().join("-vs-")}$`));
  await expect(page.getByRole("table").first()).toBeVisible();
  await page.getByLabel("Mostrar só diferenças").check();
  await page.getByRole("link", { name: "Ver ficha e ofertas" }).first().click();
  await expect(page).toHaveURL(new RegExp(`/produto/${[ids[0], ids[2]].sort()[0]}$`));
  await expect(page.getByRole("heading", { name: "Ficha técnica completa" })).toBeVisible();
  await expect(page.getByRole("button", { name: "Remover da comparação", exact: false }).first()).toBeVisible();
  await page.getByRole("link", { name: "Comparar", exact: false }).first().click();
  await expect(first).toHaveValue(ids[0]);
  await expect(second).toHaveValue(ids[2]);
  await page.reload();
  await expect(first).toHaveValue(ids[0]);
  await expect(second).toHaveValue(ids[2]);
  expect(errors).toEqual([]);
});

test("home mostra todas as categorias e navegação cabe na tela do celular", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/");
  await expect(page.locator(".catalog-meta")).toContainText("245 produtos encontrados");
  expect(new Set(await page.locator(".product-grid .category-tag").allTextContents()).size).toBeGreaterThan(1);
  await expect(page.locator(".product-grid .product-card")).toHaveCount(6);
  const logo = page.getByRole("img", { name: "ComparaCel", exact: true }).first();
  await expect(logo).toBeVisible();
  await page.getByRole("link", { name: "Categorias", exact: true }).click();
  await expect(page).toHaveURL(/\/catalogo$/);
  await expect(page.locator(".catalog-meta")).toContainText("245 produtos encontrados");
  await page.getByRole("combobox", { name: "Categoria", exact: true }).selectOption("notebooks");
  await expect(page.locator(".catalog-meta")).toContainText("17 produtos encontrados");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/catalog-mobile.png", fullPage: true });
  await page.goto("/");
  await expect(page.locator(".product-card").first()).toBeVisible();
  await page.screenshot({ path: "test-results/home-mobile.png", fullPage: true });
});


test("comparação por seções, troca no link público e ofertas em tela pequena", async ({ page }) => {
  await page.goto("/comparar");
  const first = page.getByLabel("Produto 1", { exact: true });
  await expect(first).toBeVisible({timeout:30000});
  const ids = await first.locator("option").evaluateAll(options => options.map(option => (option as HTMLOptionElement).value).filter(Boolean));
  await first.selectOption(ids[0]);
  await page.getByLabel("Produto 2", { exact: true }).selectOption(ids[2]);
  await page.getByRole("link", { name: "Ver comparação completa" }).click();
  await expect(page).toHaveURL(new RegExp(`/comparar/${[ids[0],ids[2]].sort().join("-vs-")}$`),{timeout:30000});
  await expect(page.locator(".compare-product")).toHaveCount(2);
  await expect(page.getByRole("navigation", { name: "Seções da comparação" })).toBeVisible();
  await expect(page.locator(".compare-spec-section")).not.toHaveCount(0);
  await page.screenshot({ path: "test-results/comparison-desktop.png", fullPage: true });
  const before = [ids[0], ids[2]].sort();
  await page.getByLabel("Trocar produto 1", { exact: true }).selectOption(ids[3]);
  await expect(page).toHaveURL(new RegExp(`/comparar/${[ids[3], before[1]].sort().join("-vs-")}$`));
  await expect(page.getByLabel("Trocar produto 1", { exact: true })).toHaveValue([ids[3], before[1]].sort()[0]);
  await page.reload();
  await expect(page.getByLabel("Trocar produto 2", { exact: true })).toHaveValue([ids[3], before[1]].sort()[1],{timeout:30000});
  await page.setViewportSize({ width: 390, height: 844 });
  expect(await page.locator(".comparison-account-actions button").evaluateAll(buttons=>new Set(buttons.map(button=>Math.round(button.getBoundingClientRect().top))).size)).toBe(1);
  await page.getByRole("navigation", { name: "Seções da comparação" }).getByRole("link", { name: "Preços e ofertas" }).click();
  await expect(page).toHaveURL(/#ofertas$/);
  await expect(page.locator(".compare-offers-section")).toBeInViewport();
  await expect(page.locator(".compare-sticky")).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: "test-results/comparison-mobile.png", fullPage: true });
  await page.getByRole("button", { name: "Compartilhar" }).click();
  await expect(page.locator(".share-status")).toContainText(/Link copiado|Copie o link/);
});

test("visitante encontra login e favoritos sem ver dados privados", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto("/minha-conta");
  await expect(page.getByRole("heading", { name: "Guarde seus favoritos." })).toBeVisible();
  await expect(page.locator(".account-intro").getByRole("button", { name: "Entrar com Google" })).toBeEnabled();
  await expect(page.locator(".account-tabs")).toHaveCount(0);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.goto("/");
  await expect(page.locator(".product-card").first()).toBeVisible();
  const favorite = page.locator(".product-card").first().getByRole("button", { name: "Favoritar produto" });
  await expect(favorite).toBeEnabled();
  await expect(favorite).toHaveAttribute("aria-pressed", "false");
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});

test("mais comparados filtra categorias e funciona no celular", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/comunidade');
  await expect(page.getByRole('heading', { level: 1, name: /O que o pessoal/ })).toBeVisible();
  await expect(page.getByText('Carregando comparações…')).toHaveCount(0, { timeout: 30000 });
  await expect(page.getByText('Meu perfil e favoritos')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Opiniões da comunidade' })).toHaveCount(0);
  await expect(page.locator('.community-feed').getByRole('alert')).toHaveCount(0);
  await page.getByLabel('Categoria', { exact: true }).selectOption('notebooks');
  await expect(page.getByLabel('Categoria', { exact: true })).toHaveValue('notebooks');
  await expect(page.getByText('Carregando comparações…')).toHaveCount(0, { timeout: 30000 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: 'test-results/community-mobile.png', fullPage: true });
  await page.goto('/perfil/perfil-inexistente');
  await expect(page).toHaveURL(/\/comunidade$/);
  await expect(page.getByRole('heading', { level: 1, name: /O que o pessoal/ })).toBeVisible();
});

test("contador de visitas preserva recargas e pares invertidos", async ({ page }) => {
  await page.goto('/comparar');
  const picker=page.getByLabel('Produto 1', { exact:true });
  await expect.poll(()=>picker.locator('option').count()).toBeGreaterThan(3);
  const ids=await picker.locator('option').evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value).filter(Boolean));
  await page.goto(`/produto/${ids[0]}`);
  const views=page.locator('.product-engagement .engagement-counts > span').first().locator('strong');
  await expect(views).toBeVisible({timeout:30000});
  const original=await views.innerText();
  await expect(page.getByRole('meter', {name:'Popularidade do produto'})).toBeVisible();
  await page.reload();
  await expect(views).toHaveText(original,{timeout:30000});
  await page.goto(`/comparar/${ids[0]}-vs-${ids[1]}`);
  const comparisonViews=page.locator('.comparison-engagement .engagement-counts > span').first().locator('strong');
  await expect(comparisonViews).toBeVisible({timeout:30000});
  const count=await comparisonViews.innerText();
  await page.goto(`/comparar/${ids[1]}-vs-${ids[0]}`);
  await expect(comparisonViews).toHaveText(count,{timeout:30000});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/metrics-mobile.png',fullPage:true});
  const rejected=await page.request.post('/api/engagement',{headers:{Origin:'http://localhost:3000'},data:{kind:'product',productIds:['../invalid']}});
  expect(rejected.status()).toBe(400);
});

test("cards e comparação mostram grau; apenas a página de produto permite reagir", async ({ page }) => {
  await page.goto('/');
  const card=page.locator('.product-card').first();
  await expect(card).toBeVisible({timeout:30000});
  const counters=card.locator('.inline-reaction-counts');
  await expect(counters).toBeVisible();
  await expect(counters.getByRole('button')).toHaveCount(0);
  await expect(card.locator('.product-score-circle')).not.toHaveText('—',{timeout:30000});
  await expect(card.locator('.product-score-circle')).toHaveClass(/score-provisional/);
  await card.screenshot({path:'test-results/reaction-card.png'});
  await card.getByRole('link', { name:'Ver produto' }).click();
  const reactions=page.getByRole('region', {name:'Reações ao produto'});
  for(const name of ['Não gostei','Gostei','Adorei']) await expect(reactions.getByRole('button', {name,exact:true})).toBeVisible();
  await reactions.screenshot({path:'test-results/reaction-buttons.png'});
  await page.getByText('Como os selos são definidos?').click();
  await expect(page.getByText(/Até 20 votos ou alterações/)).toBeVisible();
  await page.setViewportSize({ width:390,height:844 });
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:'test-results/reactions-product-mobile.png',fullPage:true});
  await page.goto('/comparar');
  const picker=page.getByLabel('Produto 1', {exact:true});
  await expect.poll(()=>picker.locator('option').count()).toBeGreaterThan(3);
  const ids=await picker.locator('option').evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value).filter(Boolean));
  await page.goto(`/comparar/${ids[0]}-vs-${ids[1]}`);
  await expect(page.getByRole('region', {name:'Indicador de reações do produto'})).toHaveCount(2);
  await expect(page.locator('.reaction-options')).toHaveCount(0);
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  const unauthorized=await page.request.post('/api/reactions',{headers:{Origin:'http://localhost:3000'},data:{kind:'product',productIds:[ids[0]],reaction:'sad'}});
  expect(unauthorized.status()).toBe(401);
  const crossOrigin=await page.request.post('/api/reactions',{headers:{Origin:'https://outro-site.example'},data:{kind:'product',productIds:[ids[0]],reaction:'sad'}});
  expect(crossOrigin.status()).toBe(403);
  const invalidPair=await page.request.post('/api/reactions',{headers:{Origin:'http://localhost:3000',Authorization:'Bearer invalid-token'},data:{kind:'comparison',productIds:[ids[0],ids[1]],reaction:'sad'}});
  expect(invalidPair.status()).toBe(400);
});

test("barra de comparação mostra fotos, permite remover e cabe no celular", async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('.product-card').first()).toBeVisible({timeout:30000});
  await page.getByRole('combobox',{name:'Categoria'}).selectOption('notebooks');
  await page.locator('.product-card').first().getByRole('button',{name:'Comparar',exact:true}).click();
  const bar=page.getByRole('complementary',{name:'Produtos para comparar'});
  await expect(bar.locator('.bar-photo img')).toHaveCount(1);
  await expect(bar.locator('.bar-empty')).toBeVisible();
  await page.locator('.product-card').nth(1).getByRole('button',{name:'Comparar',exact:true}).click();
  await expect(bar.locator('.bar-photo img')).toHaveCount(2);
  await expect(bar.getByRole('link',{name:'Ver comparação',exact:true})).toBeVisible();
  await expect.poll(()=>bar.locator('.bar-photo img').evaluateAll(images=>images.every(image=>(image as HTMLImageElement).naturalWidth>0))).toBe(true);
  expect((await bar.boundingBox())!.height).toBeLessThan(110);
  await bar.screenshot({path:'test-results/comparison-bar-desktop.png'});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect((await bar.boundingBox())!.height).toBeLessThan(160);
  await bar.screenshot({path:'test-results/comparison-bar-mobile.png'});
  await bar.getByRole('button',{name:/Remover .* da comparação/}).first().click();
  await expect(bar.locator('.bar-photo img')).toHaveCount(1);
  await expect(bar.locator('.bar-empty')).toBeVisible();
  await bar.getByRole('button',{name:'Limpar',exact:true}).click();
  await expect(bar).toHaveCount(0);
});

test("comunidade mostra automaticamente os pares mais comparados", async ({ page }) => {
  await page.goto('/comparar');
  const picker=page.getByLabel('Produto 1',{exact:true});
  await expect(picker).toBeVisible({timeout:30000});
  await expect.poll(()=>picker.locator('option').count()).toBeGreaterThan(3);
  const ids=await picker.locator('option').evaluateAll(options=>options.map(option=>(option as HTMLOptionElement).value).filter(Boolean));
  await page.goto(`/comparar/${ids[0]}-vs-${ids[1]}`);
  await expect(page.locator('.comparison-engagement .engagement-counts')).toBeVisible({timeout:30000});
  const response=await page.request.get('/api/popular-comparisons?category=celulares');
  expect(response.status()).toBe(200);
  const data=await response.json();
  expect(data.periodDays).toBe(7);
  expect(data.comparisons.length).toBeGreaterThan(0);
  expect(data.comparisons.every((item:{category:string;productIds:string[];views:number})=>item.category==='celulares'&&item.productIds.length===2&&item.views>0)).toBe(true);
  expect(data.comparisons[0]).not.toHaveProperty('authorUid');
  await page.goto('/comunidade');
  const ranking=page.getByRole('region',{name:'Comparações mais acessadas'});
  await expect(ranking.getByRole('heading',{name:'Mais comparados'})).toBeVisible();
  await expect(ranking.locator('.popular-pair').first()).toBeVisible({timeout:30000});
  await page.setViewportSize({width:390,height:844});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await ranking.screenshot({path:'test-results/popular-comparisons-mobile.png'});
});
